server:
  port: 8091

spring: 
  application:
    name: admin-service
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    properties:
      hibernate:
        default_schema: ${RIDESHARE_POSTGRES_1909_SCHEMA}
  # Postgres DB location and login info.
  datasource:
    url: jdbc:postgresql://${RIDESHARE_POSTGRES_1909_URL}:5432/postgres?
    username: ${RIDESHARE_POSTGRES_1909_USERNAME}
    password: ${RIDESHARE_POSTGRES_1909_PASSWORD}
      