server:
  port: 8091

spring:
  application:
    name: admin-service
  cloud:
    config:
      uri: src/main/resources/application.yml
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
