server:
  port: 8091

spring:
  application:
    name: admin-service
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    uri: postgres://ystkzprq:Z3jiUZ2pzuwX7wpCMGKHHQ2igzPpnKsl@salt.db.elephantsql.com:5432/ystkzprq
